### ISSUE TITLE
[问题]:无法使用tr paper 1.21版本

### ISSUE THREAD

**Issue by wnblm** [MCStarrySky/TrMenu#4]
### 🚀 是否已尝试最新的版本

- [X] 我已更新 TrMenu 至最新的版本, 并且同样复现该问题.

### 📚 是否已查阅 Wiki

- [X] 我已查阅 Wiki 对于该问题的相关内容, 并确定该问题是存在的.

### 🔗 是否存在重复 issue

- [X] 我已翻阅现有的 issue 没有发现内容重复, 亦或是对现有 issue 的更详细的描述.

### 📰 服务端详细信息

```
TrMenu Dump Information (Date: xxxx-xx-xx xx:xx:xx)

  | Server OS: xxxx
  | Server software: xxxx
  | Java version: xxxx

  | TabooLib: x.x.x
  | TrMenu: x.x.x
Installed Plugins:
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
  · XXXXXX - x.x.x
```

### 🔍 详细的描述

启动就无法使用

### 🗄 服务端日志

```

```
[21:05:37 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'TrMenu-3.3.4-beta1.jar' in folder 'plugins\.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:546) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:292) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:12) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:31) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.ClassField.get$default(ClassField.kt:13) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getInstance(ReflexClass.kt:84) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getInstance(ReflexClass.kt:65) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.platform.PlatformFactory.init$lambda$5(PlatformFactory.kt:68) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib$2.run(TabooLib.java:113) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:80) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib.lifeCycle(TabooLib.java:73) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.lambda$static$0(BukkitPlugin.java:48) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:35) ~[TrMenu-3.3.4-beta1.jar:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        ... 9 more
Caused by: java.lang.IllegalStateException: Unsafe not found
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.UnsafeAccess.<clinit>(UnsafeAccess.kt:34) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:12) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField$handleGetter$2.invoke(JavaClassField.kt:10) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/kotlin1822.UnsafeLazyImpl.getValue(Lazy.kt:81) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField.getHandleGetter(JavaClassField.kt:10) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassField.get(JavaClassField.kt:31) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.ClassField.get$default(ClassField.kt:13) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getInstance(ReflexClass.kt:84) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.library.reflex.ReflexClass.getInstance(ReflexClass.kt:65) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.platform.PlatformFactory.init$lambda$5(PlatformFactory.kt:68) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib$2.run(TabooLib.java:113) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib.lambda$lifeCycle$0(TabooLib.java:80) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib.lifeCycle(TabooLib.java:73) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.lambda$static$0(BukkitPlugin.java:48) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.common.TabooLib.execution(TabooLib.java:222) ~[TrMenu-3.3.4-beta1.jar:?]
        at TrMenu-3.3.4-beta1.jar/me.arasple.mc.trmenu.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:35) ~[TrMenu-3.3.4-beta1.jar:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:508) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[paper-1.21.1.jar:1.21.1-75-61fe23c]
        ... 9 more

### ⚙ 配置文件

```

```

**Comment by Micalhl** [comment]
请降级 Java 版本至 21 及以下，高版本 Java 暂不支持。

**Comment by Micalhl** [comment]
后续我会尝试在 TabooLib 中修复这个问题。
